### ISSUE TITLE
Add viglesiasce as maintainer

### ISSUE THREAD

**Issue by viglesiasce** [jenkinsci/google-source-plugin#10]
Hey folks!

Creating an issue based on this thread requesting access:
https://groups.google.com/forum/?nomobile=true#!topic/jenkinsci-dev/sGitrmkjgR8

cc @astroilov

**Comment by astroilov** [comment]
+1

**Comment by viglesiasce** [comment]
@markyjackson-taulia anything left for me to do? Who should I reach out to to flip the bit?

**Comment by markjacksonfishing** [comment]
Drop a line in the dev mailing list but everything looks good to go

**Comment by oleg-nenashev** [comment]
@viglesiasce Now you should have admin permissions in the repo.
To release a plugin, you will also need to send a PR to https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-google-source-plugin.yml

**Comment by viglesiasce** [comment]
Thanks @oleg-nenashev doing that now.

**Comment by viglesiasce** [comment]
All steps have been completed. Thanks folks!!

**Comment by oleg-nenashev** [comment]
Thank you too!
